variable "kubeconfig_path" {
  description = "Path to the Talos cluster's kubeconfig, generated by the proxmox-tofu / talosctl bootstrap."
  type        = string
  default     = "../../proxmox-tofu/_out/kubeconfig"
}

variable "namespace" {
  description = "Namespace to install auth-api into. Must already exist."
  type        = string
  default     = "clusterkeep-dev-priv"
}

variable "image_repository" {
  description = "Registry + repository for the auth-api image (the in-cluster Nexus docker-hosted repo, provisioned in cluster-config)."
  type        = string
  default     = "registry.clusterkeep.dev.net/auth-api"
}

variable "image_tag" {
  description = "For dev/preview (image_tag_prefix != \"\"): fallback tag, used only if no pushed tag matches image_tag_prefix yet. For prd (image_tag_prefix == \"\"): authoritative on every apply, so keep it in sync with the current release tag."
  type        = string
}

variable "image_tag_prefix" {
  description = "Which branch's tag channel this environment tracks: \"DEV-\", \"PREVIEW-\", or \"\" for prd."
  type        = string
  default     = "DEV-"
}

variable "image_pull_secret_name" {
  description = "Name of the imagePullSecret for the Nexus docker-hosted repo."
  type        = string
  default     = ""
}

variable "issuer_hostname" {
  description = "Hostname auth-api is served on. This is the OIDC issuer for Headlamp and, once cut over, for the Kubernetes API server's oidc-issuer-url."
  type        = string
  default     = "auth-dev.clusterkeep.dev.net"
}

variable "cookie_domain" {
  description = "Domain the SSO session cookie is scoped to. Must be a parent of both the auth-api and Headlamp hostnames for single sign-on to work."
  type        = string
  default     = ".clusterkeep.dev.net"
}

variable "headlamp_url" {
  description = "Headlamp's base URL. auth-api registers <this>/oidc-callback as the Headlamp OIDC client's only redirect URI, once cluster-auth supplies the client secret."
  type        = string
  default     = "https://headlamp.clusterkeep.dev.net"
}

variable "cluster_identity_secret_name" {
  description = "Secret written by cluster-auth holding the Headlamp client secret. Set only on the instance the apiserver trusts (prd); blank elsewhere."
  type        = string
  default     = ""
}

variable "default_redirect_url" {
  description = "Where a login without a next= target lands."
  type        = string
  default     = "https://storage-dev.clusterkeep.dev.net"
}

variable "environment" {
  description = "Environment name, surfaced on the login page and used to disable /docs in prd."
  type        = string
  default     = "dev"
}

variable "bootstrap_username" {
  description = "Admin account created on first start if it does not exist. Its generated password is a sensitive output; the account is flagged must_change_password."
  type        = string
  default     = "admin"
}

variable "bootstrap_email" {
  description = "Email for the bootstrap admin account."
  type        = string
  default     = ""
}

variable "ingress_tls_secret_name" {
  description = "Shared TLS secret (wildcard cert from the ClusterKeep internal CA), same one cluster-config's ingresses use."
  type        = string
  default     = "clusterkeep-tls"
}

variable "replica_count" {
  description = "auth-api replicas. Sessions live in Redis, so any replica can serve any request."
  type        = number
  default     = 2
}

variable "postgres_image" {
  description = "Postgres image backing auth-api's durable identity store (users, Argon2id hashes, OIDC clients, signing keys)."
  type        = string
  default     = "postgres:16"
}

variable "postgres_storage_size" {
  description = "Size of the PVC (nfs-csi StorageClass) Postgres stores auth-api's data on."
  type        = string
  default     = "5Gi"
}

variable "redis_image" {
  description = "Redis image backing sessions, authorization codes and refresh tokens. Ephemeral by design: losing it logs everyone out but destroys no accounts."
  type        = string
  default     = "redis:7-alpine"
}

variable "redis_max_memory" {
  description = "maxmemory for Redis. Reached only under an implausible number of live sessions for this cluster."
  type        = string
  default     = "256mb"
}

variable "registration_token" {
  description = "Shared bearer token that gates POST /api/v1/register. Held by clusterkeep-ui's invite-code page, not by end users."
  type        = string
  sensitive   = true
}

variable "ingress_enabled" {
  description = "Whether to create a LAN Ingress for this instance. Disable for prd - it's reached only via the Cloudflare Tunnel."
  type        = bool
  default     = true
}

variable "allowed_redirect_hosts" {
  description = "Comma-separated extra hosts login/register's next parameter may target, beyond cookie_domain and its subdomains."
  type        = string
  default     = ""
}
